---
name: CT
on: [push, pull_request]
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-20.04
    env:
      CONAN_USER: ${{ secrets.CONAN_USER }}
      CONAN_PASS: ${{ secrets.CONAN_PASS }}
    steps:
    - name: Checkout master
      uses: actions/checkout@v1.2.0